#!/usr/bin/env python3
"""
Add mobile-menu.js to all HTML pages that don't already have it.
Inserts before chatbot.js if present, otherwise before </body>.
Skips index.html (already done) and blog/ pages (regenerated via seo_phase3.py).
"""
import sys, glob
sys.stdout.reconfigure(encoding='utf-8')

SCRIPT_TAG  = '<script src="/js/mobile-menu.js" defer></script>'
CHATBOT_TAG = '<script src="/js/chatbot.js?v=10" defer></script>'
BODY_CLOSE  = '</body>'

SKIP = {'index.html'}  # already done manually

updated = 0
skipped = 0

for path in glob.glob('**/*.html', recursive=True):
    path = path.replace('\\', '/')
    # Skip index.html (root) and blog pages (regenerated by seo_phase3.py)
    if path in SKIP or path.startswith('blog/'):
        skipped += 1
        continue
    try:
        html = open(path, encoding='utf-8').read()
        if SCRIPT_TAG in html:
            skipped += 1
            continue
        if CHATBOT_TAG in html:
            html = html.replace(CHATBOT_TAG, SCRIPT_TAG + '\n' + CHATBOT_TAG)
        elif BODY_CLOSE in html:
            html = html.replace(BODY_CLOSE, SCRIPT_TAG + '\n' + BODY_CLOSE, 1)
        else:
            skipped += 1
            continue
        open(path, 'w', encoding='utf-8').write(html)
        print(f'  Updated: {path}')
        updated += 1
    except Exception as e:
        print(f'  ERROR {path}: {e}')

print(f'Done: {updated} updated, {skipped} skipped')
